on:
  push:
    branches:
      - main

jobs:
  testing-solutions:
    runs-on: python:alpine-3.8
    steps:
      - uses: actions/checkout@v2
      - name: Run candy testing
        run: |
          python3 candy/testing.py