on:
  push:
    branches:
      - main


jobs:
  testing-solutions:
    runs-on: ubuntu-latest
    steps:
      # Step 1: checkout the repo
      - name: load the repo
        uses: actions/checkout@v2
      # Step 2: run the candy tests
      - name: Run candy tests
        import: .github/actions/candy
      